# Site wide configuration

title:            Home
locale:           en_US
# // url:              http://www.moresi.info
port: 4444

# Jekyll configuration

permalink:   /posts/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap


mathjax: on
    # activated !

# Site images ethical

default-page-image: site/DSC_5374.jpg
default-post-image: site/DSCF3873.jpg

# Site owner
owner:
  name: "Louis Moresi"
  avatar: LM-SFMugShot.jpg
  bio: "Professor of Geophysics \n University of Melbourne \n Victoria 3010 Australia \n +61 4 0333 1413"
  email: louis.moresi@unimelb.edu.au
  disqus-shortname: louismoresi
  twitter: louismoresi
  facebook: louismoresi
  google:
    plus: louis.moresi@gmail.com
    analytics: UA-18255779-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: lmoresi
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: louis.moresi@unimelb.edu.au
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  researchgate: Louis_Moresi

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
